# Generated by Django 2.2.7 on 2019-11-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aname', models.CharField(max_length=100)),
                ('Aage', models.IntegerField()),
                ('Agendor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Actor_Info',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('Movi_Act', models.ManyToManyField(to='Movieapp.Actor')),
            ],
            options={
                'db_table': 'Movie_Info',
            },
        ),
    ]
